### ISSUE TITLE
Error: access key verification failed : access key not found (Code = 40110000

### ISSUE THREAD

**Issue by nba2020** [yogat3ch/AlpacaforR#12]
Hello, I've just opened an Alpaca account and trying to setup a paper trading connection in R with the below code:
```
Sys.setenv('APCA-API-KEY-ID' = 'PKCW8xxxxxxxxxI4U2SQJ')
Sys.setenv('APCA-API-SECRET-KEY' = 'CW1ZxxxxxxxxxxxxxxxxxxxxxK1QucMKI')
get_account()
```
However, I'm getting the following error in R console 

```
$code
[1] 40110000
$message
[1] "access key verification failed : access key not found (Code = 40110000)
```

**Comment by yogat3ch** [comment]
A couple of questions come to mind:
- Have you set up and fully verified an account with Alpaca?
- Have you received confirmation from Alpaca that it's been verified?
I think that API access is dependent upon verification.
Are you running Rstudio?
If so you might want to set these parameters globally. You can do so by finding the R user root directory `Sys.getenv('R_USER')` navigating to that folder, and provided that "View Hidden Files" is enabled in your File Options for the OS there should be a file called .Renviron. You can edit this with a text editor and add your ID and  key(s) as follows such that these keys persist across sessions. You'll need to restart Rstudio for the changes to take effect. :
```
APCA-PAPER-API-KEY-ID = "..."
APCA-PAPER-API-SECRET-KEY = "..."
APCA-LIVE-API-KEY-ID = "..."
APCA-LIVE-API-SECRET-KEY = "..."
```
It also appears that the documentation needs updating to reflect these changes.

**Comment by nba2020** [comment]
Thank you @yogat3ch. I eventually managed to connect for paper trading with the below:
```
Sys.setenv('APCA-PAPER-API-KEY-ID' = 'PKOxxxxxxxxxxxxxxxx2CG')
 Sys.setenv('APCA-PAPER-API-SECRET-KEY' = 'pumxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdY')
 get_account()
```

**Comment by jagg19** [comment]
hey @nba2020,

@yogat3ch hit it on the head with everything he said! Thanks to you both for pointing this out and to yoga for the pull request :)
