### ISSUE TITLE
Submitting stoplimit orders

### ISSUE THREAD

**Issue by nba2020** [yogat3ch/AlpacaforR#14]
I'm trying to fire a stoplimit orders with the example code below:

`submit_order(ticker = "ABT", qty = 1,side = "sell", type="stoplimit",limit_price = 86, stop_price = 87 )`

but I get an error:
```
$code
[1] 40010001
$message
[1] "invalid order type"
```
From the documentation of `submit_order `that should be available.
Is it because I'm submitting the order outside market opening hours?

**Comment by nba2020** [comment]
It seems like replacing `type="stoplimit"` with `type="stop_limit"` works fine. Maybe it would be good to replace in the function documentation which states "stoplimit" ;)

**Comment by jagg19** [comment]
@nba2020 

Ahh, minor spelling errors will forever be my worst enemy, haha thanks for the heads up. Will double check to make sure nothing else is mis-documented.
