### ISSUE TITLE
How to code a "take profit" order?

### ISSUE THREAD

**Issue by danielkhalilov** [yogat3ch/AlpacaforR#29]
I am trying to market buy and take profit at (ie place a limit sell above the purchased price) using jagg19/AlpacaforR. What is the easiest way to code this?

So far, I understand that the two solutions are to either:
-use yogat3ch/AlpacaforR (which may support OCO/bracket orders, though after glancing at the code, I only saw stop_limit orders, not take_profit), or 
-refactor the submit_orders function

Is there any easier way currently?

**Comment by yogat3ch** [comment]
Hi @danielkhalilov,
 yogat3ch/AlpacaforR supports all [Alpaca complex order types:  Bracket, OCO, OTO](https://alpaca.markets/docs/trading-on-alpaca/orders/). See the Readme or documentation for `order_submit` for details on how to do a take_profit order. You will want `order_class = 'bracket'` and use the `take_profit` and `stop_loss` arguments to configure accordingly.

**Comment by danielkhalilov** [comment]
Hello @yogat3ch , thank you for replying, that is so cool! I merged your code, used order_class = oto, and it works perfectly now. Great job with the enhancements!

**Comment by yogat3ch** [comment]
Awesome, good to hear it worked for you!
