### ISSUE TITLE
`firstrun` got stuck in `map2` and setting `.Renviron` didn't work either

### ISSUE THREAD

**Issue by qiuxiaomu** [yogat3ch/AlpacaforR#39]
Hi firstly thanks very much for the great work!

I am running R 4.1.2 first thing was that I can't install it just by `install.packages` I understand that the package may not be available just yet on 4.1.2; I installed the package with `devtools::install_github()`. 

I was trying to set up my credentials via `firstrun`:

`firstrun(paper_api=c(key=my_key, secret=my_secret), live_api=c(key=my_key, secret=my_secret), pro=TRUE, live=FALSE)`

it didn't work and from the stack trace I can see that it got stuck after `map2`. There was not error message whatsoever it simply jumped to a break point, halted. 

setting these params in `.Renviron` didn't work either. I got a `request is not authorized` when I was trying to request market data.

**Comment by yogat3ch** [comment]
Hey @stucash,
Thanks for the issue report!
Unfortunately, I'm pretty overloaded right now. I can see about taking a look at it possibly by tomorrow night (EST), or next Wednesday night (EST).

Thanks for your patience,
Stephen

**Comment by yogat3ch** [comment]
Hey @stucash,
I took a look at this but didn't get anywhere because there were more issues than just this one. I've built some new functions that handle adding environmental variables more gracefully recently so I'll see if I can fix this one tomorrow morning.

**Comment by qiuxiaomu** [comment]
@yogat3ch thanks for fixing it! I have not tried the new version just yet I'll give it a go this week.
