### ISSUE TITLE
Minor Modifications to Documentation for get_bars

### ISSUE THREAD

**Issue by yogat3ch** [yogat3ch/AlpacaforR#4]
Hey there,
*UPDATE 2019-07-14*
I was getting errors in using get_bars related to the as.POSIXct conversion and I believe it was due to the fact that the sapply pulls out a list of dates when more than one ticker is passed and the as.POSIXct is only designed to vectorize over vectors rather than lists. 
Trying to run through the code manually I found that the else statements aren't being interpreted due to the newlines preceding them. 
I went ahead and rewrote some of the sections with these ifelse statements such that it executes properly when run from the source editor. 
I also reworked the output from the GET call using dplyr to return POSIXct for the time column (and remove rather than cbind the superfluous integer date column), and to rename the variables to quantmod standard names as I know many in the R finance coder community use this package and it's functions require columns to be named as "open", "high", "low" ,"close" etc. 

The code for the new function is as follows:
```
function (ticker, from = Sys.Date() - 6, to = Sys.Date(), timeframe = "1D", 
  limit = NULL) 
{
  url = "https://data.alpaca.markets"
  headers = get_headers()
  if (!is.null(limit)) {
    if (limit > 1000) {
      stop("Max limit is 1000!")
    }
  }
  ticker = ifelse(length(ticker) > 1, paste0(ticker, collapse = ","), 
    ticker)
  week_dates = get_calendar(from, to)$date
  if (length(week_dates) > 1000) {
    start <- length(week_dates) - 999
    week_dates <- week_dates[start:length(week_dates)]
  }
  if ((timeframe == "1D" | timeframe == "day") & is.null(limit)) {
    limit = length(week_dates)
  } else if (timeframe == "15Min" & is.null(limit)) {
    limit = 250
  } else if (timeframe == "5Min" & is.null(limit)) {
    limit = 500
  } else if ((timeframe == "1Min" | timeframe == "minute") & is.null(limit)) {
    limit = 1000
  }
  if (!(timeframe == "1D" | timeframe == "day")) {
    from = paste0(from, stringr::str_extract(format(Sys.time(), 
      "%Y-%m-%dT%H:%M:%OS%z"), "T.*"))
    to = paste0(to, stringr::str_extract(format(Sys.time(), 
      "%Y-%m-%dT%H:%M:%OS%z"), "T.*"))
  } else {
    from = paste0(from, "T20:30:00-04:00")
    to = paste0(to, "T20:30:00-04:00")
  }
  bars = httr::GET(url = paste0(url, "/v1/bars/", timeframe, 
    "?symbols=", ticker, "&limit=", limit, "&start=", from, 
    "&end=", to), headers)
  bars = response_text_clean(bars)
  bars = lapply(bars, function(l){
    nms <- c(time = "t", open = "o", high = "h", low = "l", close = "c", volume = "v")
    out <- dplyr::mutate_at(l, dplyr::vars("t"), dplyr::funs(as.POSIXct, .args = list(origin = "1970-01-01"))) %>% dplyr::mutate_at(dplyr::vars(o,h,c,l,v),dplyr::funs(as.numeric)) %>%
      dplyr::rename((!!nms))
    })
  return(bars)
}
```
On a related note, a suggestion for future development is to create a vector of GET requests executed in serial to accommodate `from` values that are older than 1000 bars will cover.  

My previous suggestion regarding the documentation has been updated to account for the changes to the column names as per the suggestion above. 

Suggestions for the @return section of get_bars to indicate that the type of object returned is a list, v is in millions, and the addition of column d that is a POSIXct. I tested the knitting of this with Roxygen, it formats nicely with the first line as the return value and then an indented list for the data.frame columns.
```
#' @return \code{list} object for each ticker symbol containing a \code{data.frame} with the following columns:
#' \itemize{
#'  \item{\code{time}}{  the time of the bar as \code{POSIXct} in yyyy-mm-dd for timeframe = day, and yyyy-mm-dd hh:mm:ss for timeframes < day}
#'  \item{\code{open}}{  open price as a numeric object.}
#'  \item{\code{high}}{  high price as a numeric object.}
#'  \item{\code{low}}{  low price as a numeric object.}
#'  \item{\code{close}}{  close price as a numeric object.}
#'  \item{\code{volume}}{  volume (in millions) as a numeric object.}
#' }
```

An aside, I'm finding that running the example on get_bars:
`get_bars(ticker = c("INTC","MSFT"))`
leads to the following warning messages:
```
Warning messages:
  1: In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
2: In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
```
I can view the list object, and then when I click to view an individual data.frame object within that list, the R session aborts entirely. 
I'll see if I can troubleshoot the cause, otherwise I just wanted to let you know about it in case you want to try to replicate it or have an intuition as to what might be causing it.

Thanks!

**Comment by jagg19** [comment]
Thanks once again @yogat3ch for your feedback and suggestions, all of this is a ton of help. To be honest, I did not like the `cbind` and `sapply` combination I was implementing for the new date column, and this is exactly what I'd like to use. I didn't use the deprecating `funs` but used the warnings suggestions of implementing lambda `~`.

`out <- dplyr::mutate_at(l, dplyr::vars("t"), ~as.POSIXct(.,origin = "1970-01-01")) %>% dplyr::mutate_at(dplyr::vars(o,h,c,l,v), ~as.numeric(.)) %>%
      dplyr::rename((!!nms))`

I'm trying to see where in the `ifelse` statements were wrong on my end. When you say "I found that the else statements aren't being interpreted due to the newlines preceding them. I went ahead and rewrote some of the sections with these ifelse statements such that it executes properly when run from the source editor." What do you mean by the new lines preceding them? I can't see where you rewrote the `ifelse` statements in your code above.

With that said, I kept the ifelse statements the same from my most recent upload of `get_bars` in AlpacaforR and added your initial suggestion from #3. It all seems to run fine on my end so I also will add this new suggestion. Let me know if it's working as planned for you also.

Also, thanks for the new roxygen documentation for `@return`. I like the list format. I added the new documentation in but are you sure that the volume is shown in millions??? I left that part out because the `v` or volume column on my end is showing the full integer value. If I viewed a low-volatile stock like "RPAY" with a volume under 1 million, it shows the full integer value. Same for highly volatile stocks like "AMD". Sorry if I am misunderstanding your statement about volume. 

Last, it seems like the warning message from the example is stemming from `cbind` from the current `get_bar` function that is loaded in AlpacaforR.

`dates = sapply(bars,"[[","t") 
  bars = lapply(bars,cbind,d = as.POSIXct(dates, origin = "1970-01-01"))`

This no longer happens with the new `get_bars` function that I am going to push now. Im not too sure if something changed since the last time I updated `get_bars` that's caused these errors but it should be good to go with these updates. 

Lmk if this fixes are good enough to close issue #3 and #4

**Comment by yogat3ch** [comment]
Hi @jagg19 ,
Thanks for the response!

> I didn't use the deprecating `funs` but used the warnings suggestions of implementing lambda `~`.

Very cool, I didn't know the tilde anonymous function formatting worked with dplyr as it does for purrr. That's good to know! 

> `out <- dplyr::mutate_at(l, dplyr::vars("t"), ~as.POSIXct(.,origin = "1970-01-01")) %>% dplyr::mutate_at(dplyr::vars(o,h,c,l,v), ~as.numeric(.)) %>% dplyr::rename((!!nms))`

Looks good!

> I'm trying to see where in the `ifelse` statements were wrong on my end. When you say "I found that the else statements aren't being interpreted due to the newlines preceding them. I went ahead and rewrote some of the sections with these ifelse statements such that it executes properly when run from the source editor." What do you mean by the new lines preceding them? I can't see where you rewrote the `ifelse` statements in your code above.

Sorry, I can see how this wording was confusing. What I was referring to is the if {...} else {...} conditional flow code having new lines in places that caused the code to error when running from the source editor. Example to follow:
The way the function appeared for me in the editor (as a reprex): 
```
# The Reprex part
timeframe <- "15Min"
limit <- NULL
# Code from the actual function as it displays in the source editor
if ((timeframe == "1D" | timeframe == "day") & is.null(limit)) {
    limit = length(week_dates)
  }
  else if (timeframe == "15Min" & is.null(limit)) {
    limit = 250
  }
``` 
Result:
Error: unexpected 'else' in "else"
>     limit = 250
> }
Error: unexpected '}' in "}"

I think this is caused by the new line between the closing bracket } and the call to else if. 
The reformatting that I did was as follows:
```
# The Reprex part
timeframe <- "15Min"
limit <- NULL
# Fixed code
if ((timeframe == "1D" | timeframe == "day") & is.null(limit)) {
    limit = length(week_dates)
  } else if (timeframe == "15Min" & is.null(limit)) { # just a space between } and else
    limit = 250
  }
print(c(timeframe,limit))
```

Result: 
[1] "15Min" "250" 

> With that said, I kept the ifelse statements the same from my most recent upload of `get_bars` in AlpacaforR and added your initial suggestion from #3. It all seems to run fine on my end so I also will add this new suggestion. Let me know if it's working as planned for you also.

Yes, for some reason when get_bars is compiled and called from within the package it runs fine, it only seems to error when running from the source editor. Up to you if you'd like to change it or not.

Just an addition that might be helpful to add flexibility to the way the timeframe argument is specified. This makes it such that m, min, Mins, Minutes, minutes, days, d etc are all valid entries. Probably best added near the top of the function.
```
  if (stringr::str_detect(timeframe, stringr::regex("D|d|days?", ignore_case = T))) {
    timeframe <- "1D"
  } else if (stringr::str_detect(timeframe, stringr::regex("M|mins?|minutes?", ignore_case = T))) {
    timeframe <- paste0(stringr::str_extract(timeframe, "^\\d+"),"Min")
    }
```
A reprex to illustrate:
```
expand.grid(n = c(1,5,15), ti = c("m","min","mins","minutes","days","day","d","D")) %>% purrr::pmap_chr(function(n,ti){
   timeframe <- paste0(n,ti)
   message(paste0("Original:", timeframe))
  if (stringr::str_detect(timeframe, stringr::regex("D|d|days?", ignore_case = T))) {
    timeframe <- "1D"
  } else if (stringr::str_detect(timeframe, stringr::regex("M|mins?|minutes?", ignore_case = T))) {
    timeframe <- paste0(stringr::str_extract(timeframe, "^\\d+"),"Min")
  }
   message(timeframe)
   return(timeframe)
   })
```

> Also, thanks for the new roxygen documentation for `@return`. I like the list format.

Certainly!

> I added the new documentation in but are you sure that the volume is shown in millions??? I left that part out because the `v` or volume column on my end is showing the full integer value. If I viewed a low-volatile stock like "RPAY" with a volume under 1 million, it shows the full integer value. Same for highly volatile stocks like "AMD". Sorry if I am misunderstanding your statement about volume.

I'm getting the volume as an integer value too - I think I just misinterpreted the results I was receiving. My bad.
 
> Last, it seems like the warning message from the example is stemming from `cbind` from the current `get_bar` function that is loaded in AlpacaforR.
> 
> `dates = sapply(bars,"[[","t") bars = lapply(bars,cbind,d = as.POSIXct(dates, origin = "1970-01-01"))`
> 
> This no longer happens with the new `get_bars` function that I am going to push now. Im not too sure if something changed since the last time I updated `get_bars` that's caused these errors but it should be good to go with these updates.

Looking good! Now quantmod compatible as is!
I'll leave this open until we conclude the bit about the regex for the timeframe argument.

**Comment by jagg19** [comment]
@yogat3ch Now I understand and see the if else error!! Always the little formatting errors that get me. Needed a fresh pair of eyes to see it haha thanks. 

>Yes, for some reason when get_bars is compiled and called from within the package it runs fine, it only seems to error when running from the source editor. Up to you if you'd like to change it or not.

Is it still giving you an error? If so, I would like to try and fix it. Can you screenshot your error or if you know specifically where it is, open a pull request if you have time?


>Just an addition that might be helpful to add flexibility to the way the timeframe argument is specified. This makes it such that m, min, Mins, Minutes, minutes, days, d etc are all valid entries. Probably best added near the top of the function.

Nice, love the idea (and format of these comments haha) but I will exclude `ignore_case = T` from the "Min" timeframes to avoid any confusion between a month and minute timeframes. If someone uses "3m" expecting 3-month chart and instead get a bunch of minute bars. It's a little clearer in my opinion if it's abbreviated at the minimum "min" for minute and "mon" for month (if month timeframe is ever added). I went ahead and pushed the new addition. If all works well then you can go ahead and close this! 

I will be camping for the next 6 days in upstate NY :) Talk after! Enjoy the week.

**Comment by yogat3ch** [comment]
Camping in upstate NY sounds great! I hope that's an awesome adventure! 
Cool, I didn't know there could be support for month long periods in the future, given that's the case it sounds like the modification without `ignore_case  = T` sounds more appropriate. 

Regarding the if else, I commented inline on the commit - the code shows up fine in the github code editor. I think the issue is an artifact of how the RStudio read only function definition viewer formats the code.

Let's consider this closed! Thanks for your consideration!

**Comment by yogat3ch** [comment]
Hi @jagg19,
It looks like I missed the default use case scenario with the timeframe modification. 

We need a small modification to handle when there are no digits specified for timeframe. 

I've forked the repo and created a branch called [timeframe](https://github.com/yogat3ch/AlpacaforR/tree/timeframe) that implements the fix.

I think you should be able to pull/merge them or just change it yourself at line 560

```
 digit <- ifelse(!is.na(stringr::str_extract(timeframe, "^\\d+")), stringr::str_extract(timeframe, "^\\d+"), "1")
    timeframe <- paste0(digit,"Min")
```

**Comment by jagg19** [comment]
>Camping in upstate NY sounds great! I hope that's an awesome adventure!

It really was a great adventure! I always enjoy getting away every once in a while. 

>Cool, I didn't know there could be support for month long periods in the future

I don't think alpaca will add this functionality to their API, but I may add it to the function (more of a personal preference). I look at a lot of m/m and q/q data so it would come in handy.

I am going to go ahead and merge your pull request for this change, thanks!!
