### ISSUE TITLE
Unable to call functions in AlpacaforR

### ISSUE THREAD

**Issue by brianfleharty** [yogat3ch/AlpacaforR#42]
Quick update,

It turns out that the V1 was retired last week and now the functions changed and there is a r environment key needed from polygon which can be obtained by creating an account.

id<-'your id'
secret_key<-'your secret'
POLYGON_K<- 'your polygon key'

Sys.setenv('APCA-LIVE-API-KEY-ID' = id)
Sys.setenv('APCA-LIVE-API-SECRET-KEY' = secret_key)
Sys.setenv('POLYGON-KEY' = POLYGON_K) 

https://github.com/yogat3ch/AlpacaforR#arguments-to-market_data-for-the-v2-api

Hello,

Recently after trying to reinstall AlpacaforR after uninstalling and reinstalling R I get the notification below.  

I tried uninstalling and reinstalling because of a recent inability to get stock prices from code which had previously been working for over a year.  Any idea what could be causing this or how to fix?  My issues seem to be getting worse.  First it was only the get_bars() function not returning stock prices and now the functions arent being found.

####First error after returning from vacation from code that broke while running over vacation.
get_bars(ticker = "FB", time="minute", limit=5)
Error in UseMethod("tbl_vars") :
  no applicable method for 'tbl_vars' applied to an object of class "character"

####Second error after uninstalling and reinstalling
library(AlpacaforR)

Attaching package: ‘AlpacaforR’

The following object is masked from ‘package:graphics’:

    polygon

Thank You,

Brian

**Comment by yogat3ch** [comment]
Hi @brianfleharty,
Sorry to hear about the issues you're having.
The V1 API was soft-deprecated more than a year ago. `get_bars` is from a version of AlpacaforR that has been overhauled and it now no longer present in the package. I changed the function names to match the API v2 documentation directly for interpretability.
I think the only option is for you to refactor your code using the new package functions which will hopefully work more reliably for you. I hope that's helpful!
