### ISSUE TITLE
BUG: (Error when submitting trailing percent order with AlpacaforR::order_submit()) Error in `rlang::call_args()`:

### ISSUE THREAD

**Issue by bnilsson7** [yogat3ch/AlpacaforR#47]
### Bug Description
**Expected behavior**
Expected to successfully order a trail percent with the code for example:
bo <- AlpacaforR::order_submit(watchList[i,1], side = "buy", q = 3, type = "market",time_in_force = "ioc") ## This works great!
ts_0 <- AlpacaforR::order_submit(bo,trail_percent = 5) #This is where the error is thrown
**Actual Behavior**
When I try to order a trail percent shown above, I get the error:
Error in `rlang::call_args()`:
! `call` must be a defused call, not NULL.

The error is thrown inside the function AlpacaforR::order_submit(), specifically:
ca <- rlang::call_args(tail(rlang::trace_back(bottom = 1)$calls, 
            1)[[1]])
#Example

library(AlpacaforR)

Sys.setenv('APCA-PAPER-KEY' = "")
Sys.setenv('APCA-PAPER-SECRET' = "")
Sys.setenv("APCA-LIVE" = FALSE)

positions<-data.frame(try(AlpacaforR::positions()))

orders<-AlpacaforR::orders(status="closed")
bo19<-which(orders$order_type=="market" & orders$side == "buy")

boughtorders<-orders[bo19,]
bo20<-which(positions$symbol %in% boughtorders$symbol)

currentpositions<-boughtorders[bo20,]

symbolID<-currentpositions$symbol[1]
symbolID
[1] "APYX"
client_order_id<-currentpositions$client_order_id[1]
client_order_id
[1] "6fc87c20-251a-47a9-92f2-b59859abc39e"
ts_0<-AlpacaforR::order_submit(symbolID, client_order_id = client_order_id,trail_percent = 5)
Error in `rlang::call_args()`:
! `call` must be a defused call, not NULL.
Run `rlang::last_error()` to see where the error occurred.

sessionInfo()

Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2
 os       macOS 
 system   x86_64
 ui       RStudio
 language (EN)
 rstudio  2022.12.0+353 Elsbeth Geranium
 pandoc   NA

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] AlpacaforR_1.0.1

</details>

**Comment by yogat3ch** [comment]
Hey @Buccodibeppo,
Sorry for the delay on this, slammed with deadlines at work.
It should be fixed now, but you'll need to specify a quantity and the `client_order_id` needs to be unique - you can just let the server handle making a unique id. Does this help you to do what you were intending to do?
`AlpacaforR::order_submit("APYX", trail_percent = 5, qty = 1)`

**Comment by bnilsson7** [comment]
Hi @yogat3ch,

It works, thank you very much!
