### ISSUE TITLE
Suggestion for all `_order(s)` functions

### ISSUE THREAD

**Issue by yogat3ch** [yogat3ch/AlpacaforR#5]
The `_order(s)` type requests return a data.frame with all character formatted objects, which makes the values therein not very conducive to manipulation R. I've started to use the same chunk of code in manipulating the output from all of the _order type functions over and over again so I thought I'd post it here if you want to just add it in to the end of each function to change the output data types to be readily manipulable in R.

```
AlpacatoR_order_mutate <- function(df) {
  toNum <- function(x){
    as.numeric(stringr::str_replace_all(x, "\\$|\\,", ""))
  }
  df <- dplyr::mutate_at(df, dplyr::vars(dplyr::ends_with("at")),dplyr::funs(lubridate::ymd_hms(., tz = Sys.timezone())))
  out <- dplyr::mutate_at(df, dplyr::vars(qty, filled_qty, filled_avg_price, limit_price, stop_price), dplyr::funs(toNum))
  return(out)
}
```
Depends:

- dplyr
- lubridate
- stringr

Additionally, here's one for get_positions that changes all of those character numbers to actual numerics:
```
AlpacatoR_position_mutate <- function(df) {
 out <- dplyr::mutate_at(df, tidyselect::vars_select(names(df), "qty", "market_value", "cost_basis", "change_today", dplyr::starts_with("unr"), dplyr::ends_with("price")), dplyr::funs(as.numeric))
  return(out)
}
```
Depends are tidyselect - but this is a suggest of dplyr so it should already be installed if dplyr is already in the AlpacaforR depends.

**Comment by jagg19** [comment]
Hi @yogat3ch Awesome! 

Sorry for the late response on these issues that you've opened. For some reason, I must have missed the email notifications, but I will review all the issues now.

The `AlpacatoR_order_mutate` looks good, although I would like to find an alternative to using `funs` in `dplyr::` since according to the warning it is going to be deprecated pretty soon. I'm not too familiar with `funs`, but it suggests in the warning to use a list of lambdas so the below does the same thing:

`AlpacatoR_order_mutate <- function(df) {

    toNum <- function(x){
    as.numeric(stringr::str_replace_all(x, "\\$|\\,", ""))
  }

    df <- dplyr::mutate_at(df, dplyr::vars(dplyr::ends_with("at")),list(~lubridate::ymd_hms(., tz =    Sys.timezone())))

    out <- dplyr::mutate_at(df, dplyr::vars(qty, filled_qty, filled_avg_price, limit_price, stop_price), list(toNum))

    return(out)

}`



You gave me an idea with your suggestions for `get_positions` which I will also incorporate. This does the same thing as your suggestions, except I'll use the map function with the compound assignment operator from `purrr` & `magrittr::` package:

`AlpacatoR_position_mutate <- function(df) {

    df[,c(5:6,8:ncol(df))] %<>% purrr::map_dbl(as.numeric)
    return(df)

}`


We can use numeric indexing like this since I believe the output from Alpaca's /orders endpoint is going to remain the same. I believe `dplyr::` is already in AlpacaforR imports so it shouldn't be an issue if you want to stick with `tidyselect::`. 

Let me know what you think! Thanks

**Comment by yogat3ch** [comment]
Hi @jagg19,
> Sorry for the late response on these issues that you've opened. For some reason, I must have missed the email notifications, but I will review all the issues now.

No worries, grateful for a response anytime you get around to it!

> The `AlpacatoR_order_mutate` looks good, although I would like to find an alternative to using `funs` in `dplyr::` since according to the warning it is going to be deprecated pretty soon. I'm not too familiar with `funs`, but it suggests in the warning to use a list of lambdas so the below does the same thing:
> 
> `AlpacatoR_order_mutate <- function(df) {
> 
> ```
> toNum <- function(x){
> as.numeric(stringr::str_replace_all(x, "\\$|\\,", ""))
> ```
> 
> }
> 
> ```
> df <- dplyr::mutate_at(df, dplyr::vars(dplyr::ends_with("at")),list(~lubridate::ymd_hms(., tz =    Sys.timezone())))
> 
> out <- dplyr::mutate_at(df, dplyr::vars(qty, filled_qty, filled_avg_price, limit_price, stop_price), list(toNum))
> 
> return(out)
> ```
> 
> }`

Thanks for the suggestions! I've used funs all over the place O_o - I'll have to do a find & replace in files. For now I've updated the AlpacatoR functions I've been using with the lambda syntax as suggested.
 
> You gave me an idea with your suggestions for `get_positions` which I will also incorporate. This does the same thing as your suggestions, except I'll use the map function with the compound assignment operator from `purrr` & `magrittr::` package:
> 
> `AlpacatoR_position_mutate <- function(df) {
> 
> ```
> df[,c(5:6,8:ncol(df))] %<>% purrr::map_dbl(as.numeric)
> return(df)
> ```
> 
> }`



> We can use numeric indexing like this since I believe the output from Alpaca's /orders endpoint is going to remain the same. I believe `dplyr::` is already in AlpacaforR imports so it shouldn't be an issue if you want to stick with `tidyselect::`.
> 
> Let me know what you think! Thanks

This is even simpler, love it! Implement as you see fit!

**Comment by jagg19** [comment]
@yogat3ch the good ol' find & replace savior haha closing this issue here. Thanks!

**Comment by yogat3ch** [comment]
Hi @jagg19 ,
It looks like the more condensed call to purr::map_dbl is throwing an exception, screenshotted below:
![image](https://user-images.githubusercontent.com/32208821/61913830-54483f00-af0c-11e9-94a9-09905db27a89.png)
The error is due to map_dbl output expecting a single numeric. 
A simple fix is to change the two instances on [lines 188](https://github.com/jagg19/AlpacaforR/blob/fbde27056cec1cbd11c14539845bcb4e0c887100/R/alpaca4R.R#L188) and 191 to map_dfc. A simple find & replace should do the trick.

I hope you enjoyed your time camping!

**Comment by yogat3ch** [comment]
Hi @jagg19,
Update as of 2019-08-02
I've forked the repo and implemented this fix in a branch entitled [get_positions](https://github.com/yogat3ch/AlpacaforR/tree/get_positions)

**Comment by jagg19** [comment]
Thanks @yogat3ch, going to merge this in. Hope all is well on your end!
